# Generated by Django 5.1.1 on 2024-09-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('house_number', models.CharField(max_length=10)),
                ('house_size', models.CharField(choices=[('1', '1 Bedroom'), ('2', '2 Bedrooms'), ('3', '3 Bedrooms')], max_length=1)),
            ],
        ),
    ]
