# Generated by Django 5.1.1 on 2024-09-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='move_in_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
